### ISSUE TITLE
login

### ISSUE THREAD

**Issue by allanpoulsen** [Yelp/docker-observium#14]
Got the image up and running, but what's the default login ?

**Comment by allanpoulsen** [comment]
I guess there isn't any, until adduser.php has been used. Now I am in :-)

**Comment by raitkook** [comment]
This container is not supported anymore, still works but in future, you may have PHP problems.

**Comment by allanpoulsen** [comment]
It is working fine, with PHP warnings :-) Do you know of any other ( supported ) container-versions of observium?

**Comment by raitkook** [comment]
Search here: https://hub.docker.com/search?q=observium&type=image
